{{- if .Values.oauth.enabled -}}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    k8s-app: oauth2-proxy
    app: {{ template "suxen.name" . }}
    chart: {{ template "suxen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: oauth2-proxy
        image: {{ .Values.oauth.image }}
        imagePullPolicy: IfNotPresent
        args:
        {{- range $key, $value := .Values.oauth.extraArgs }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
        {{- end }}
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ .Values.oauth.clientId }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ .Values.oauth.clientSecret }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: {{ .Values.oauth.cookieSecret }}
        ports:
        - containerPort: 4180
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
        resources:
{{ toYaml .Values.oauth.resources | indent 10 }}
    {{- with .Values.oauth.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.oauth.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
