apiVersion: v1
kind: Service
metadata:
  name: {{ template "suxen.fullname" . }}
  labels:
    app: {{ template "suxen.name" . }}
    chart: {{ template "suxen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $portOption := .Values.service.ports }}
  - name: {{ $portOption.name }}
    port: {{ $portOption.port }}
    {{- if $portOption.protocol }}
    protocol: {{ $portOption.protocol }}
    {{- end -}}
    {{- if $portOption.targetPort }}
    targetPort: {{ $portOption.targetPort }}
    {{- end -}}
  {{- end }}
  selector:
    app: {{ template "suxen.name" . }}
    release: {{ .Release.Name }}
